package uy.urudin.persistance.model;
// Generated May 20, 2019 7:52:35 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import uy.urudin.datatypes.DTMonederohistorico;

/**
 * Monederohistorico generated by hbm2java
 */
@Entity
@Table(name = "monederohistorico", schema = "urudin")
public class Monederohistorico implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	private Cliente cliente;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	private Date fecha;
	
	@Column(name = "saldoanterior", nullable = false)
	private int saldoanterior;
	
	@Column(name = "motivo", nullable = false, length = 10)
	private String motivo;
	
	@Column(name = "monto", nullable = false)
	private int monto;
	
	@Column(name = "idtransaccion", length = 200)
	private String idtransaccion;

	public Monederohistorico() {
	}

	public Monederohistorico(int id, Cliente cliente, Date fecha, int saldoanterior, String motivo, int monto) {
		this.id = id;
		this.cliente = cliente;
		this.fecha = fecha;
		this.saldoanterior = saldoanterior;
		this.motivo = motivo;
		this.monto = monto;
	}

	public Monederohistorico(int id, Cliente cliente, Date fecha, int saldoanterior, String motivo, int monto,
			String idtransaccion) {
		this.id = id;
		this.cliente = cliente;
		this.fecha = fecha;
		this.saldoanterior = saldoanterior;
		this.motivo = motivo;
		this.monto = monto;
		this.idtransaccion = idtransaccion;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}


	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}


	public int getSaldoanterior() {
		return this.saldoanterior;
	}

	public void setSaldoanterior(int saldoanterior) {
		this.saldoanterior = saldoanterior;
	}


	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}


	public int getMonto() {
		return this.monto;
	}

	public void setMonto(int monto) {
		this.monto = monto;
	}


	public String getIdtransaccion() {
		return this.idtransaccion;
	}

	public void setIdtransaccion(String idtransaccion) {
		this.idtransaccion = idtransaccion;
	}

	public Monederohistorico(DTMonederohistorico dtMonederohistorico) {
		super();
		this.id = dtMonederohistorico.getId();
		Cliente cliente= new Cliente(dtMonederohistorico.getDtcliente());
		this.cliente = cliente;
		this.fecha = dtMonederohistorico.getFecha();
		this.saldoanterior = dtMonederohistorico.getSaldoanterior();
		this.motivo = dtMonederohistorico.getMotivo();
		this.monto = dtMonederohistorico.getMonto();
		this.idtransaccion = dtMonederohistorico.getIdtransaccion();
	}
	
	
	public DTMonederohistorico getDTMonederohistorico() {
		return new DTMonederohistorico(
				this.id,
				this.cliente.getDTCliente(),
				this.fecha,
				this.saldoanterior,
				this.motivo,
				this.monto,
				this.idtransaccion
				);
	}
	
	
}
