package uy.urudin.persistance.model;
// Generated Apr 9, 2019 11:18:31 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notificacion generated by hbm2java
 */
@Entity
@Table(name = "notificacion", schema = "public")
public class Notificacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Cliente cliente;
	private String cabezal;
	private String cuerpo;
	private String status;
	private boolean leido;

	public Notificacion() {
	}

	public Notificacion(int id, Cliente cliente, boolean leido) {
		this.id = id;
		this.cliente = cliente;
		this.leido = leido;
	}

	public Notificacion(int id, Cliente cliente, String cabezal, String cuerpo, String status, boolean leido) {
		this.id = id;
		this.cliente = cliente;
		this.cabezal = cabezal;
		this.cuerpo = cuerpo;
		this.status = status;
		this.leido = leido;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "cabezal", length = 100)
	public String getCabezal() {
		return this.cabezal;
	}

	public void setCabezal(String cabezal) {
		this.cabezal = cabezal;
	}

	@Column(name = "cuerpo", length = 500)
	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "leido", nullable = false)
	public boolean isLeido() {
		return this.leido;
	}

	public void setLeido(boolean leido) {
		this.leido = leido;
	}

}
