package uy.urudin.persistance.model;
// Generated Apr 9, 2019 9:35:51 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import uy.urudin.datatypes.DTParametro;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "parametro", schema = "public")
public class Parametro implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@Column(name = "nombre", nullable = false, length = 100)
	private String nombre;
	@Column(name = "valor", nullable = false, length = 100)
	private String valor;

	public Parametro() {
	}

	public Parametro(int id, String nombre, String valor) {
		this.id = id;
		this.nombre = nombre;
		this.valor = valor;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public Parametro(DTParametro dtParameter) {
		this.id = dtParameter.getId();
		this.nombre = dtParameter.getNombre();
		this.valor = dtParameter.getValor();
	}
	
	public DTParametro getDTParametro() {
		return new DTParametro(this.getId(),this.getNombre(),this.getValor());
	}
	
}
