package uy.urudin.persistance.model;
// Generated Apr 9, 2019 5:34:28 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import uy.urudin.datatypes.datatypes.DTParametro;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "parametro", schema = "test")
public class Parametro implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
		
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@Column(name = "name", nullable = false, length = 100)
	private String name;
	
	@Column(name = "value", nullable = false, length = 100)
	private String value;

	public Parametro() {
	}

	public Parametro(int id, String name, String value) {
		this.id = id;
		this.name = name;
		this.value = value;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	public Parametro(DTParametro dtParameter) {
		this.id = dtParameter.getId();
		this.name = dtParameter.getName();
		this.value = dtParameter.getValue();
	}
	
	public DTParametro getDTParametro() {
		return new DTParametro(this.getId(),this.getName(),this.getValue());
	}


}
