package uy.urudin.persistance.model;
// Generated Apr 9, 2019 11:18:31 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name = "registro", schema = "public")
public class Registro implements java.io.Serializable {

	private int id;
	private Cliente cliente;
	private Scooter scooter;
	private Date fecha;

	public Registro() {
	}

	public Registro(int id, Cliente cliente, Scooter scooter) {
		this.id = id;
		this.cliente = cliente;
		this.scooter = scooter;
	}

	public Registro(int id, Cliente cliente, Scooter scooter, Date fecha) {
		this.id = id;
		this.cliente = cliente;
		this.scooter = scooter;
		this.fecha = fecha;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idscooter", nullable = false)
	public Scooter getScooter() {
		return this.scooter;
	}

	public void setScooter(Scooter scooter) {
		this.scooter = scooter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
