package uy.urudin.persistance.model;
// Generated Apr 9, 2019 11:18:31 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Scooterhistorico generated by hbm2java
 */
@Entity
@Table(name = "scooterhistorico", schema = "public")
public class Scooterhistorico implements java.io.Serializable {

	private ScooterhistoricoId id;
	private String latitud;
	private String longitud;
	private Integer bateria;

	public Scooterhistorico() {
	}

	public Scooterhistorico(ScooterhistoricoId id) {
		this.id = id;
	}

	public Scooterhistorico(ScooterhistoricoId id, String latitud, String longitud, Integer bateria) {
		this.id = id;
		this.latitud = latitud;
		this.longitud = longitud;
		this.bateria = bateria;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idscooter", column = @Column(name = "idscooter", nullable = false)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 29)) })
	public ScooterhistoricoId getId() {
		return this.id;
	}

	public void setId(ScooterhistoricoId id) {
		this.id = id;
	}

	@Column(name = "latitud", length = 30)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", length = 30)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@Column(name = "bateria")
	public Integer getBateria() {
		return this.bateria;
	}

	public void setBateria(Integer bateria) {
		this.bateria = bateria;
	}

}
