package uy.urudin.persistance.model;
// Generated Apr 9, 2019 11:18:31 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScooterhistoricoId generated by hbm2java
 */
@Embeddable
public class ScooterhistoricoId implements java.io.Serializable {

	private int idscooter;
	private Date fecha;

	public ScooterhistoricoId() {
	}

	public ScooterhistoricoId(int idscooter, Date fecha) {
		this.idscooter = idscooter;
		this.fecha = fecha;
	}

	@Column(name = "idscooter", nullable = false)
	public int getIdscooter() {
		return this.idscooter;
	}

	public void setIdscooter(int idscooter) {
		this.idscooter = idscooter;
	}

	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScooterhistoricoId))
			return false;
		ScooterhistoricoId castOther = (ScooterhistoricoId) other;

		return (this.getIdscooter() == castOther.getIdscooter())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdscooter();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
