select * from parametro;
--insert into parametro(nombre,valor) values('test','1')
select * from scooter;
--insert into scooter(latitud,longitud,bateria) values('lat','long',99)
select * from cliente;
--insert into cliente(email) values('molivera1991@gmail.com')
select * from notificacion;
--insert into notificacion(cabezal,cuerpo,status,idcliente) values('cabezal','cuerpo','status',1)
select * from registro;
--insert into registro(idscooter,idcliente) values(1,1)
select * from  scooterhistorico;
--insert into scooterhistorico(idscooter,latitud,longitud,bateria) values(1,'lat','long',99)
select * from movimientos;
--insert into movimientos(idviaje,monto) values(1,5)